sidebar:
  
  entries:
  - title: 适用于 Microsoft 365 的 NetApp SaaS Backup
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: 新增功能
      url: "/reference_new_saasbackupO365.html"
    - title: 新增功能归档
      url: "/reference_new_archived.html"
    - title: 已知问题和限制
      url: "/reference_kpls.html"
  - title: 概念
    entries:
    - title: 概述
      url: "/concept_overview.html"
    - title: 可与 SaaS Backup 结合使用的存储类型
      url: "/concept_storage_types.html"
  - title: 入门
    entries:
    - title: 开始免费试用
      entries:
      - title: 工作流
        url: "/concept_free_trial_workflow.html"
      - title: 免费试用限制
        url: "/concept_free_trial_restrictions.html"
      - title: 注册获取免费试用激活代码
        url: "/task_registering_for_free_trial_activation_code.html"
      - title: 注册 Microsoft 365 免费试用帐户
        url: "/task_signing_up_for_o365_free_trial.html"
      - title: 创建具有全局权限的 Microsoft 365 服务帐户
        url: "/task_creating_msservice_account_with_global_permissions.html"
      - title: 为 Microsoft Exchange Online 配置模拟
        url: "/task_configuring_impersonation.html"
      - title: 注册申请免费试用 SaaS Backup for Microsoft 365
        url: "/task_signing_up_for_saasbkup_free_trial.html"
      - title: 计划首次备份
        url: "/task_scheduling_first_backup.html"
      - title: 执行 imdate 备份
        url: "/task_performing_immediate_backup_of_policy.html"
      - title: 从试用订阅升级
        entries:
        - title: 升级
          url: "/task_upgrading_from_trial.html"
        - title: 升级后激活支持
          url: "/task_activate_support.html"
      - title: 免费试用数据删除
        url: "/reference_free_trial_data.html"
    - title: 开始使用付费订阅
      entries:
      - title: 工作流
        url: "/concept_paid_subscription_workflow.html"
      - title: 创建具有全局权限的 MS Office 服务帐户
        url: "/task_creating_msservice_account_with_global_permissions.html"
      - title: 为 Microsoft Exchange Online 配置模拟
        url: "/task_configuring_impersonation.html"
      - title: 注册订阅 SaaS Backup for Microsoft 365 的付费订阅
        url: "/task_signing_up_for_saasbkup_paid_subscription.html"
      - title: 计划首次备份
        url: "/task_scheduling_first_backup.html"
      - title: 执行 imdate 备份
        url: "/task_performing_immediate_backup_of_policy.html"
      - title: 付费订阅数据删除
        url: "/reference_paid_subscription_data.html"
  - title: 管理服务
    entries:
    - title: 激活服务
      url: "/task_activating_a_service.html"
    - title: 停用服务
      url: "/task_deactivating_a_service.html"
    - title: 激活支持
      url: "/task_activate_support.html"
    - title: 发现新的邮箱，站点和组
      url: "/task_discovering_new.html"
    - title: 清除用户，站点集或 Microsoft 365 组
      url: "/task_purging.html"
  - title: 管理设置
    entries:
    - title: 备份策略
      url: "/concept_backup_policies.html"
    - title: 备份设置
      url: "/concept_backup_settings.html"
    - title: 设置通知
      url: "/task_setting_account_notifications.html"
    - title: 权限
      entries:
      - title: 向服务帐户添加权限
        url: "/task_adding_permissions_to_service_accounts.html"
      - title: 将用户权限与 Azure Active Directory 同步
        url: "/task_syncing_user_permissions_with_azure.html"
      - title: 授予启用共享邮箱的权限
        url: "/task_granting_permissions_to_enable_shared_mailboxes.html"
    - title: 基于角色的帐户访问
      entries:
      - title: 为用户帐户分配管理角色
        url: "/task_assigning_admin_roles_to_user_accounts.html"
      - title: 更新分配给用户帐户的管理角色
        url: "/task_updating_admin_roles_assigned_to_user_accounts.html"
      - title: 删除用户帐户中的所有管理角色
        url: "/task_deleting_admin_roles_from_a_user_account.html"
  - title: 管理用户
    entries:
    - title: licenses
      entries:
      - title: 添加许可证
        url: "/task_adding_a_license.html"
      - title: 更新订阅信息
        url: "/task_updating_subscription_information.html"
      - title: 释放用户许可证
        url: "/task_releasing_a_user_license.html"
    - title: rules
      entries:
      - title: 创建新规则
        url: "/task_creating_rules.html"
      - title: 应用现有规则
        url: "/task_applying_rules.html"
      - title: 删除规则
        url: "/task_deleting_rules.html"
    - title: 安全组
      entries:
      - title: 添加安全组
        url: "/task_adding_security_groups.html"
      - title: 删除安全组
        url: "/task_deleting_security_groups.html"
  - title: 管理备份
    entries:
    - title: 计划备份或更改备份频率
      url: "/task_scheduling_backup_or_changing_frequency.html"
    - title: 立即执行备份
      url: "/task_performing_immediate_backup_of_service.html"
    - title: 浏览备份
      url: "/task_browsing_backups.html"
    - title: 取消作业
      url: "/task_canceling_job.html"
    - title: 更新备份保留期限
      url: "/task_updating_backup_retention_period.html"
    - title: 为 OneNote 启用备份
      url: "/task_enabling_onenote_backups.html"
    - title: Microsoft SharePoint Online 中支持备份的模板和应用程序
      url: "/concept_supported_templates_and_apps.html"
  - title: 管理还原
    entries:
    - title: 关于还原
      url: "/reference_about_restores.html"
    - title: 执行高级别还原
      url: "/task_performing_high_level_restore.html"
    - title: 执行粒度级还原
      entries:
      - title: 对于 Exchange
        url: "/task_performing_granular_level_restore_exchange.html"
      - title: 对于 SharePoint
        url: "/task_performing_granular_level_restore_sharepoint.html"
      - title: 适用于 OneDrive
        url: "/task_performing_granular_level_restore_onedrive.html"
      - title: 适用于组和团队
        url: "/task_performing_granular_level_restore_teams.html"
    - title: 从先前备份还原
      url: "/task_restoring_from_previous_backup.html"
    - title: 取消作业
      url: "/task_canceling_job.html"
    - title: 查找已还原的文件
      url: "/task_viewing_restore_file_locations.html"
  - title: 查看数据
    entries:
    - title: 创建用户定义的筛选器
      url: "/task_creating_user_defined_filter.html"
    - title: 执行搜索
      url: "/task_performing_search.html"
    - title: 使用高级搜索
      url: "/task_using_advanced_search.html"
    - title: 查看作业历史记录和活动日志
      url: "/task_viewing_history_and_activity.html"
    - title: 查看已取消配置的项
      url: "/task_viewing_deprovisioned.html"
    - title: 查看已清除的数据
      url: "/task_viewing_purged.html"
    - title: 查看已删除的项
      url: "/task_viewing_deleted.html"
    - title: 下载数据
      url: "/task_downloading_data.html"
    - title: 监控用户数据
      url: "/task_monitoring_data.html"
  - title: 提供反馈
    url: "/task_providing_feedback.html"
  - title: 从何处获取帮助和查找更多信息
    url: "/concept_get_help_find_info.html"
  - title: 法律声明
    url: "/reference_legal_notices.html"
